[package]
name = "payment-plan"
version = "0.1.0"
edition = "2021"


[dependencies]
prost = "0.12.6"
core_payment_plan = { path ="../core" }
chrono = { version = "0.4.38" }
clap = "4.5.7"

[build-dependencies]
prost-build = "0.12.6"
