[workspace]
resolver = "2"

members = ["core", "cli" ,"uniffi-bindgen","generators/node","generators/wasm", "generators/uniffi"]


[profile.release]
strip = true


[profile.release-unstripped]
inherits = "release"
strip = "debuginfo"