[workspace]
resolver = "2"

members = ["core", "node", "cli", "wasm", "uniffi" ,"uniffi-bindgen"]


[profile.release]
strip = true


[profile.release-unstripped]
inherits = "release"
strip = "debuginfo"