[package]
name = "payment_plan_uniffi"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib", "cdylib"]
name = "payment_plan_uniffi"

[dependencies]
uniffi = "0.29.1"
core_payment_plan = { path ="../core" }
chrono = { version = "0.4.38", features = ["serde"] }