name: Continuous Integration

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
permissions:
  contents: read

jobs:
  run-cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler

      - name: Run cargo tests
        run: cargo test

      - name: Run node tests
        run: cd node && npm ci && npm test