name: Continuous Integration

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
permissions:
  contents: read

jobs:
  run-cargo-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0
      - name: Run cargo tests
        run: cargo test

  run-node-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run node tests
        run: cd node && npm ci && npm test

  run-wasm-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run wasm tests
        run: cd wasm && npm ci && npm test