name: Continuous Integration

on:
  pull_request:
    branches: [master]
    paths-ignore:
      - "**/*.md"
permissions:
  contents: read

jobs:
  build-sdks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clean up
        run: make clean
      - name: Install mingw-w64
        run: sudo apt-get update && sudo apt-get install -y mingw-w64
      - name: Install windows target
        run: rustup target add x86_64-pc-windows-msvc
      - name: build go sdk
        run: make build-go-sdk

  run-cargo-tests:
    needs: build-sdks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0
      - name: Run cargo tests
        run: cargo test

  run-node-tests:
    needs: build-sdks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Run node tests
        run: cd node && npm ci && npm test

  run-wasm-tests:
    needs: build-sdks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: jetli/wasm-pack-action@v0.4.0
        with:
          version: "latest"

      - name: Run wasm tests
        run: cd wasm && npm ci && npm test

  run-cli-tests:
    needs: build-sdks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: Install protoc
        run: sudo apt-get update && sudo apt-get install -y protobuf-compiler
      - name: Setup protoc
        uses: arduino/setup-protoc@v3.0.0
      - name: Install protoc-gen-go
        run: go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
      - name: Add Go cli to PATH
        run: |
          echo 'export PATH=$PATH:$(go env GOPATH)/cli' >> $GITHUB_PATH
      - name: Run cli tests
        run: cd cli && make test

  run-go-tests:
    needs: build-sdks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: "1.24"
      - name: run go tests
        run: cd sdks/go && go test -v ./...
