name: Release Package

on:
  release:
    types: [created]

jobs:
  publish-web:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - name: Publish to GitHub Package Registry
        run: |
          cd wasm/lib
          echo "Publish to GitHub Package Registry"
          export NODE_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}
          npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  publish-node:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    # Prevent a situation where native build fails and an npm package is uploaded.
    needs: [nodejs-github-native]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
          registry-url: https://npm.pkg.github.com/
      - name: Set release version
        # Set release version in all three os, the commented run should suffice for linux and mac.
        run: python3 -c "import os; tag = os.environ['GITHUB_REF'].split('/')[-1]; f = open(os.environ['GITHUB_ENV'], 'a'); f.write('RELEASE_VERSION='+tag); f.close();"
        # run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Tweak package.json
        # This will update the package version to tag version and
        # add an install script in package.json so users who `npm i` this package
        # will trigger the node-pre-gyp to pull the os and arch specific binary.
        run: python3 -c "import os; import json; p = json.load(open('./node/package.json')); p['scripts']['install'] = 'node-pre-gyp install'; p['version'] = os.environ['RELEASE_VERSION']; json.dump(p, open('./node/package.json', 'w'), indent=2, ensure_ascii=False);"
      - name: Publish to GitHub Package Registry
        run: |
          cd node
          cat package.json
          echo "Publish to GitHub Package Registry"
          export NODE_AUTH_TOKEN=${{secrets.GITHUB_TOKEN}}
          npm publish --registry=https://npm.pkg.github.com/
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

  nodejs-github-native:
    name: nodejs-${{ matrix.node_version }}-${{ matrix.system.target }}-${{ matrix.system.os }}
    runs-on: ${{ matrix.system.os }}
    strategy:
      fail-fast: false
      matrix:
        node_version:
          - 20
          - 22
        system:
          # apple-darwin is being skipped because the runner is taking too long to start.
          #- os: macos-11
          #target: x86_64-apple-darwin
          - os: ubuntu-20.04
            target: x86_64-unknown-linux-gnu
          - os: windows-2022
            target: x86_64-pc-windows-msvc
          # Would like to have aarch64 support, but actions does not provide these yet.
          # https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.release.tag_name }}
      - name: Set release version
        # Set release version in all three os, the commented run should suffice for linux and mac.
        run: python3 -c "import os; tag = os.environ['GITHUB_REF'].split('/')[-1]; f = open(os.environ['GITHUB_ENV'], 'a'); f.write('RELEASE_VERSION='+tag); f.close();"
        # run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node_version }}
          registry-url: "https://registry.npmjs.org"
      - name: Install modules
        run: cd node && npm i
      - name: Tweak package.json
        # This will update the package version to tag version. So artifacts uploaded to Github release will be named correctly.
        run: python3 -c "import os; import json; p = json.load(open('./node/package.json')); p['version'] = os.environ['RELEASE_VERSION']; json.dump(p, open('./node/package.json', 'w'), indent=2, ensure_ascii=False);"

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: stable
          target: ${{ matrix.system.target }}
          override: true

      - name: Build native
        run: cd node && npm run build:qitech # for now we are using qitech
      - name: Package the asset
        # This will make a node-pre-gyp package.
        run: cd node && npx node-pre-gyp package
      - name: Upload to Github releases
        # Use bash, even on Windows to make find available
        shell: bash
        # A release need to be created before upload
        run: gh release upload ${{ env.RELEASE_VERSION }} "$(find ./node/build -name *.tar.gz)" --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-go-sdk:
    name: Deploy Go SDK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Copy Go SDK to a temporary directory
        run: |
          mkdir -p go-sdk
          cp -r sdks/go/* go-sdk/

      - name: Push Go SDK to public repository
        env:
          REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
        run: |
          cd go-sdk
          git init
          git remote add origin https://x-access-token:${REPO_TOKEN}@github.com/ParceladoLara/payment-plan-go-sdk.git
          git add .
          git commit -m "Deploy Go SDK"
          git branch -M main
          git push -f origin main

# This job is for musl based linux systems.(not working yet)
#  nodejs-github-native-musl:
#    name: musl-branch-${{ matrix.branch }}-x86_64-unknown-linux-musl-${{ matrix.system.os }}
#    runs-on: ubuntu-20.04
#    strategy:
#      fail-fast: false
#      matrix:
#        branch:
#          - v3.21 #nodejs 22
#          - v3.20 #nodejs 20
#        system:
#          - os: ubuntu-20.04
#            target: x86_64-unknown-linux-musl
#    steps:
#      - uses: actions/checkout@v2
#        with:
#          ref: ${{ github.event.release.tag_name }}
#      - name: Set release version
#        # Set release version in all three os, the commented run should suffice for linux and mac.
#        run: python3 -c "import os; tag = os.environ['GITHUB_REF'].split('/')[-1]; f = open(os.environ['GITHUB_ENV'], 'a'); f.write('RELEASE_VERSION='+tag); f.close();"
#        # run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
#
#      - name: Setup latest Alpine Linux
#        uses: jirutka/setup-alpine@v1
#
#      - name: install nodejs
#        run: |
#          echo "http://dl-cdn.alpinelinux.org/alpine/${{matrix.branch}}/main" > /etc/apk/repositories
#          apk update
#          apk add --no-cache nodejs
#        shell: alpine.sh --root {0}
#
#      - name: install npm
#        # i'm hardcoding the version of npm here, because the version of npm in the alpine repo is too old.
#        run: |
#          echo "http://dl-cdn.alpinelinux.org/alpine/v3.21/community" > /etc/apk/repositories
#          apk update
#          apk add npm
#        shell: alpine.sh --root {0}
#
#      - name: install cargo
#        run: |
#          echo "https://dl-cdn.alpinelinux.org/alpine/edge/main/" > /etc/apk/repositories
#          apk update
#          apk upgrade --ignore nodejs --ignore npm
#          apk add cargo
#        shell: alpine.sh --root {0}
#
#      - name: Install modules
#        run: |
#          cd node
#          npm i
#        shell: alpine.sh --root {0}
#
#      - name: Tweak package.json
#        # This will update the package version to tag version. So artifacts uploaded to Github release will be named correctly.
#        run: python3 -c "import os; import json; p = json.load(open('./node/package.json')); p['version'] = os.environ['RELEASE_VERSION']; json.dump(p, open('./node/package.json', 'w'), indent=2, ensure_ascii=False);"
#
#      - name: Build native
#        run: |
#          cd node
#          npm run build:qitech
#        shell: alpine.sh --root {0}
#
#      - name: Package the asset
#        run: |
#          cd node
#          npx node-pre-gyp package
#        shell: alpine.sh --root {0}
#
#      - name: Upload to Github releases
#        # Use bash, even on Windows to make find available
#        shell: bash
#        # A release need to be created before upload
#        run: gh release upload ${{ env.RELEASE_VERSION }} "$(find ./node/build -name *.tar.gz)" --clobber
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
